### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by Tramac** [Thinklab-SJTU/ThinkMatch#24]
I trained on two GPUs. where `yaml` as follows:
```
# available GPU ids
GPUS:
  - 0
  - 1
```

But there was an error:
```
Traceback (most recent call last):
  File "train_eval.py", line 309, in <module>
    xls_wb=wb)
  File "train_eval.py", line 99, in train_eval_model
    outputs = model(inputs)
  File "/home/pyenv/gm_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pyenv/gm_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 156, in forward
    return self.gather(outputs, self.output_device)
  File "/home/ThinkMatch/src/parallel/data_parallel.py", line 18, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 85, in gather
    return gather_map(outputs)
  File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 79, in gather_map
    for k in out))
  File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 79, in <genexpr>
    for k in out))
  File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 80, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 71, in gather_map
    return concatenate(*outputs, device=target_device)
  File "/home/ThinkMatch/src/sparse_torch/csx_matrix.py", line 458, in concatenate
    indptr_offset += mat.indptr[-1]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```

Many appreciate if got any reply!

**Comment by rogerwwww** [comment]
Hi there,

I will look into this issue. In the meantime, does it work if you use only one GPU?

**Comment by Tramac** [comment]
@rogerwwww Thank you for your reply! Everything works fine when using a GPU.

**Comment by Lin-Yijie** [comment]
Hi, I find the same error when setting GPUs in .yaml like:
# available GPU ids
GPUS:
  - 0
  - 1
 
Has the code implemented the DataParallel for Multi-GPUs? Many appreciate if got any reply! @rogerwwww 


> I trained on two GPUs. where `yaml` as follows:
> 
> ```
> # available GPU ids
> GPUS:
>   - 0
>   - 1
> ```
> 
> But there was an error:
> 
> ```
> Traceback (most recent call last):
>   File "train_eval.py", line 309, in <module>
>     xls_wb=wb)
>   File "train_eval.py", line 99, in train_eval_model
>     outputs = model(inputs)
>   File "/home/pyenv/gm_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/pyenv/gm_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 156, in forward
>     return self.gather(outputs, self.output_device)
>   File "/home/ThinkMatch/src/parallel/data_parallel.py", line 18, in gather
>     return gather(outputs, output_device, dim=self.dim)
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 85, in gather
>     return gather_map(outputs)
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 79, in gather_map
>     for k in out))
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 79, in <genexpr>
>     for k in out))
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 80, in gather_map
>     return type(out)(map(gather_map, zip(*outputs)))
>   File "/home/ThinkMatch/src/parallel/scatter_gather.py", line 71, in gather_map
>     return concatenate(*outputs, device=target_device)
>   File "/home/ThinkMatch/src/sparse_torch/csx_matrix.py", line 458, in concatenate
>     indptr_offset += mat.indptr[-1]
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

**Comment by rogerwwww** [comment]
Hi, we have prioritized this issue and we are looking into this. Hoping to get a fix very soon.

**Comment by rogerwwww** [comment]
Dear all, I am trying to reproduce your issue, what is the yaml file used in your experiments?

**Comment by Lin-Yijie** [comment]
> Dear all, I am trying to reproduce your issue, what is the yaml file used in your experiments?

It seems that each yaml will cause such problem if the available GPU in yaml more than 1:

# available GPU ids
GPUS:
  - 0
  - 1

**Comment by rogerwwww** [comment]
Please refer to my recent commit, and the issue for the multi-GPU parallel shall be fixed now. It seems to be due to newer PyTorch versions. If you have any further questions, feel free to open new issues or reopen this issue.

**Comment by Lin-Yijie** [comment]
Hi Runzhong. There still exists a multi-gpu problem. When running ngmv2 with 2 gpu (e.g., vgg16_ngmv2_voc.yaml),

`Traceback (most recent call last):
  File "/home/simon/Code/ThinkMatch-master/train_eval.py", line 331, in <module>
    xls_wb=wb)
  File "/home/simon/Code/ThinkMatch-master/train_eval.py", line 90, in train_eval_model
    outputs = model(inputs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/Code/ThinkMatch-master/models/NGM/model_v2.py", line 96, in forward
    graph = self.message_pass_node_features(graph)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/Code/ThinkMatch-master/models/BBGM/sconv_archs.py", line 47, in forward
    result = self.mp_network(graph)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/Code/ThinkMatch-master/models/BBGM/sconv_archs.py", line 33, in forward
    xs += [F.relu(conv(xs[-1], edge_index, edge_attr))]
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simon/anaconda3/envs/matching/lib/python3.7/site-packages/torch_geometric/nn/conv/spline_conv.py", line 126, in forward
    out += torch.matmul(x_r, self.root)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`


Process finished with exit code 1
`

**Comment by dragonbg** [comment]
I'm getting a problem using google collab saying both cpu and gpu are being used when the tensor device is just cuda:0

**Comment by rogerwwww** [comment]
@dragonbg Could you provide more details (like what command are you running)? So that we can investigate what is going wrong.
